[project]
name = "flask_app"
description = "simple flask app example"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "flask",
    "flask-mysqldb",
    "Flask-WTF",
    "passlib",
    ]

[project.optional-dependencies]
test = ["pytest"]

